/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2023-05-07 17:38:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.learn.mycart.entities.User;
import com.learn.mycart.dao.CategoryDao;
import com.learn.mycart.entities.Category;
import com.learn.mycart.helper.FactoryProvider;
import java.util.List;
import com.learn.mycart.entities.User;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/components/common_css_js.jsp", Long.valueOf(1682755900259L));
    _jspx_dependants.put("/components/message.jsp", Long.valueOf(1682750758892L));
    _jspx_dependants.put("/components/navbar.jsp", Long.valueOf(1683395729150L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.learn.mycart.entities.Category");
    _jspx_imports_classes.add("com.learn.mycart.helper.FactoryProvider");
    _jspx_imports_classes.add("com.learn.mycart.dao.CategoryDao");
    _jspx_imports_classes.add("com.learn.mycart.entities.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	User user = (User) session.getAttribute("current-user");
	if (user == null) {
		session.setAttribute("message", "You are not logged in !! Please Login");
		response.sendRedirect("login.jsp");
		return;
	} else {
		if (user.getUserType().equals("normal")) {
			session.setAttribute("message", "User is Not Authorized to Access Admin Panel");
			response.sendRedirect("login.jsp");
			return;
		}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!--css-->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- javascript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"js/script.js\"></script>");
      out.write("\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Admin</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');

		User user1 = (User)session.getAttribute("current-user");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark navbar mb-3 bg-body-tertiary mycart-bg\">\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"index.jsp\">MyCart</a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNavDropdown\" aria-controls=\"navbarNavDropdown\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarNavDropdown\">\r\n");
      out.write("      <ul class=\"navbar-nav\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"index.jsp\">Home</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">Features</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">Pricing</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Categories\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>      \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    ");

    
    if(user1 == null){
    
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("      	<li class=\"nav-item active\">\r\n");
      out.write("      		<a class=\"nav-link\" href=\"login.jsp\">Login</a>\r\n");
      out.write("      	</li>\r\n");
      out.write("      	<li class=\"nav-item active\">\r\n");
      out.write("      		<a class=\"nav-link\" href=\"register.jsp\">Register</a>\r\n");
      out.write("      	</li>\r\n");
      out.write("      	      \r\n");
      out.write("      </ul>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
	
    	
    }
    
    
    
    
    
    else{
    	
    
      out.write("\r\n");
      out.write("    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("      	<li class=\"nav-item active\">\r\n");
      out.write("      		<a class=\"nav-link\" href=\"#!\">");
      out.print( user1.getUserName() );
      out.write("</a>\r\n");
      out.write("      	</li>\r\n");
      out.write("      	<li class=\"nav-item active\">\r\n");
      out.write("      		<a class=\"nav-link\" href=\"logoutServlet\">Logout</a>\r\n");
      out.write("      	</li>\r\n");
      out.write("      	      \r\n");
      out.write("      </ul>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
	
    	
    	
    }
    
    
    
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<h1>Admin</h1>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container admin\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("			");
  
String message = (String)session.getAttribute("message");
if(message != null)
{

//	out.println(message);
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"alert alert-success alert-dismissible fade m-1 show\" role=\"alert\">\r\n");
      out.write("  <strong>");
      out.print(message );
      out.write("</strong>\r\n");
      out.write("  <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
	
	
	
	session.removeAttribute("message");
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<!-- first col -->\r\n");
      out.write("			<div class=\"col-md-4 \">\r\n");
      out.write("				<div class=\"card \">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<div class=\"container\">\r\n");
      out.write("							<img style=\"max-width: 100px;\" class=\"img-fluid\"\r\n");
      out.write("								src=\"img/all users.png\" alt=\"users\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<h1>2342</h1>\r\n");
      out.write("						<h1 class=\"text-muted\">USERS</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- second col -->\r\n");
      out.write("			<div class=\"col-md-4\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"card\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<div class=\"container\">\r\n");
      out.write("							<img style=\"max-width: 100px;\" class=\"img-fluid\"\r\n");
      out.write("								src=\"img/categories.png\" alt=\"categories\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<h1>23</h1>\r\n");
      out.write("						<h1 class=\"text-muted\">CATEGORIES</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- third col -->\r\n");
      out.write("			<div class=\"col-md-4\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"card\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<div class=\"container\">\r\n");
      out.write("							<img style=\"max-width: 100px;\" class=\"img-fluid\"\r\n");
      out.write("								src=\"img/products.png\" alt=\"products\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<h1>151</h1>\r\n");
      out.write("						<h1 class=\"text-muted\">PRODUCTS</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- First row end -->\r\n");
      out.write("\r\n");
      out.write("		<!-- second row start -->\r\n");
      out.write("		<div class=\"row mt-3\">\r\n");
      out.write("\r\n");
      out.write("			<!-- second row 1st col -->\r\n");
      out.write("			<div class=\"col-md-6\">\r\n");
      out.write("				<div class=\"card\" data-bs-toggle=\"modal\"\r\n");
      out.write("					data-bs-target=\"#add-category-modal\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<div class=\"container\">\r\n");
      out.write("							<img style=\"max-width: 100px;\" class=\"img-fluid\"\r\n");
      out.write("								src=\"img/add category.png\" alt=\"products\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<h1>151</h1>\r\n");
      out.write("						<h1 class=\"text-muted\">ADD CATEGORY</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- second row 2nd col -->\r\n");
      out.write("			<div class=\"col-md-6\">\r\n");
      out.write("				<div class=\"card\" data-bs-toggle=\"modal\"\r\n");
      out.write("					data-bs-target=\"#add-product-modal\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<div class=\"container\">\r\n");
      out.write("							<img style=\"max-width: 100px;\" class=\"img-fluid\"\r\n");
      out.write("								src=\"img/add product.png\" alt=\"products\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<h1>151</h1>\r\n");
      out.write("						<h1 class=\"text-muted\">ADD PRODUCTS</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- add category modal starts-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"add-category-modal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header mycart-bg\">\r\n");
      out.write("					<h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">ADD\r\n");
      out.write("						CATEGORY</h1>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("					<form action=\"productOperationServlet\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("						<input type=\"hidden\" name=\"operation\" value=\"addCategory\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"form-group mb-2\">\r\n");
      out.write("						 <label for=\"cTitle\">Category Title</label>\r\n");
      out.write("							<input id=\"cTitle\" type=\"text\" class=\"form-control\" name=\"catTitle\"\r\n");
      out.write("								placeholder=\"Enter category title\" required />\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"cDesc\">Category Description</label>\r\n");
      out.write("							<textarea id=\"cDesc\" style=\"height: 300px\" class=\"form-control\"\r\n");
      out.write("								name=\"catDescription\" placeholder=\"Enter Category discription\"\r\n");
      out.write("								required></textarea>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"container text-center\">\r\n");
      out.write("							<button class=\"btn btn-outline-success m-2\">Add Category\r\n");
      out.write("							</button>\r\n");
      out.write("							<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("								data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- add category modal ends-->\r\n");
      out.write("\r\n");
      out.write("	<!-- add product modal starts -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Button trigger modal -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"add-product-modal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header mycart-bg\">\r\n");
      out.write("					<h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">ADD\r\n");
      out.write("						PRODUCT</h1>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("					<!-- form start -->\r\n");
      out.write("					<form action=\"productOperationServlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("					\r\n");
      out.write("						<input type=\"hidden\" name=\"operation\" value=\"addProduct\">\r\n");
      out.write("\r\n");
      out.write("						<!-- product title -->\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							\r\n");
      out.write("							<label for=\"pName\">Product Title:</label>\r\n");
      out.write("							<input type=\"text\" id=\"pName\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"Enter product title\" name=\"pName\" required>\r\n");
      out.write("						\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- product description -->\r\n");
      out.write("\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"pDesc\">Product Description:</label>\r\n");
      out.write("							<textarea id=\"pDesc\" style=\"height: 150px;\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"Enter product description\" name=\"pDesc\"></textarea>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- product price -->\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("						<label for=\"pPrice\">Product Price:</label>\r\n");
      out.write("							<input id=\"pPrice\" type=\"number\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"Enter product price\" name=\"pPrice\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- product discount -->\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("						 <label for=\"pDiscount\">Product Discount:</label>\r\n");
      out.write("							<input id=\"pDiscount\" type=\"number\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"Enter product discount\" name=\"pDiscount\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- product quantity -->\r\n");
      out.write("						\r\n");
      out.write("										\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("						 <label for=\"pQuantity\">Product Quantity:</label>\r\n");
      out.write("							<input id=\"pQuantity\" type=\"number\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"Enter product quantity\" name=\"pQuantity\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- product category -->\r\n");
      out.write("						");

						
						CategoryDao cdao = new CategoryDao(FactoryProvider.getFactory());
						List<Category> list=cdao.getCategories();
						
						
      out.write("\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("						 <label for=\"pCat\">Product Category:</label>\r\n");
      out.write("							<select id=\"pCat\" name=\"catId\" class=\"form-control\" required>\r\n");
      out.write("							");
 for(Category c: list){
							
      out.write("\r\n");
      out.write("								<option value=\"");
      out.print(c.getCategoryId() );
      out.write('"');
      out.write('>');
      out.print(c.getCategoryTitle() );
      out.write("</option>\r\n");
      out.write("								\r\n");
      out.write("							");
} 
      out.write("\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- product pic -->\r\n");
      out.write("\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"pPic\">Select product pic</label>\r\n");
      out.write("							 <br>\r\n");
      out.write("							  <input type=\"file\" id=\"pPic\" name=\"pPic\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"container text-center mt-2\">\r\n");
      out.write("\r\n");
      out.write("							<button class=\"btn btn-outline-success m-2\">Add product</button>\r\n");
      out.write("							<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("								data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</form>\r\n");
      out.write("					<!-- form end -->\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- add product modal ends -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
